receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

connectors:
  spanmetrics:
    namespace: traces_span_metrics

    histogram:
      explicit:
        buckets:
          - 2ms
          - 4ms
          - 6ms
          - 8ms
          - 10ms
          - 50ms
          - 100ms
          - 200ms
          - 400ms
          - 800ms
          - 1s
          - 1400ms
          - 2s
          - 5s
          - 10s

exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-export
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, spanmetrics, googlecloud]
    metrics:
      receivers: [spanmetrics]
      processors: [batch]
      exporters: [prometheus, googlecloud]
