"""initial_schema

Revision ID: 07360b5c199c
Revises: 
Create Date: 2026-05-02 13:01:52.002624

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07360b5c199c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisors',
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('advisor_id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('students',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('current_risk_status', sa.String(), nullable=False),
    sa.Column('intervention_status', sa.String(), nullable=False),
    sa.Column('last_notified_timestamp', sa.Double(), nullable=False),
    sa.Column('last_notified_satisfaction', sa.Integer(), nullable=False),
    sa.Column('draft_job_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('user',
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('activities',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('test_type', sa.String(), nullable=True),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('timestamp', sa.Double(), nullable=True),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('advisor_points_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.advisor_id'], ),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention_emails',
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.advisor_id'], ),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('student_status_history',
    sa.Column('history_id', sa.Uuid(), nullable=False),
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('baseline_avg', sa.Double(), nullable=True),
    sa.Column('baseline_std', sa.Double(), nullable=True),
    sa.Column('current_score_avg', sa.Double(), nullable=True),
    sa.Column('z_score', sa.Double(), nullable=True),
    sa.Column('anomaly_flag', sa.String(), nullable=True),
    sa.Column('status_recorded_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_status_history')
    op.drop_table('intervention_emails')
    op.drop_table('advisor_points_ledger')
    op.drop_table('activities')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('students')
    op.drop_table('idempotency_keys')
    op.drop_table('advisors')
    # ### end Alembic commands ###
