"""Add advisor profile fields

Revision ID: cc13aad9a8cb
Revises: ef96aa80c6b7
Create Date: 2026-05-05 17:55:24.633369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc13aad9a8cb'
down_revision: Union[str, Sequence[str], None] = 'ef96aa80c6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('office', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('office')
        batch_op.drop_column('faculty')
        batch_op.drop_column('phone')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
