"""make_user_keep_advisor_id

Revision ID: f3e08ae42c77
Revises: a3e26ba4a778
Create Date: 2026-05-06 11:25:37.721175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision: str = 'f3e08ae42c77'
down_revision: Union[str, Sequence[str], None] = 'a3e26ba4a778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('office', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq__advisors__user_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk__advisors__user_id__user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', src.infrastructure.database.models.UTCDateTime(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advisor_id', sa.Uuid(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq__user__advisor_id'), ['advisor_id'])
        batch_op.create_foreign_key(batch_op.f('fk__user__advisor_id__advisors'), 'advisors', ['advisor_id'], ['advisor_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__user__advisor_id__advisors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq__user__advisor_id'), type_='unique')
        batch_op.drop_column('advisor_id')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.CHAR(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk__advisors__user_id__user'), 'user', ['user_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq__advisors__user_id'), ['user_id'])
        batch_op.drop_column('bio')
        batch_op.drop_column('office')
        batch_op.drop_column('faculty')
        batch_op.drop_column('phone')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
