"""add ai overview columns to case

Revision ID: 4c4866c96803
Revises: 7a4263c7f8f7
Create Date: 2026-05-13 20:17:58.209068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4866c96803'
down_revision: Union[str, Sequence[str], None] = '7a4263c7f8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('action_keys', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('action_keys')
        batch_op.drop_column('academic_summary')

    # ### end Alembic commands ###
