"""add_outbox_event_table

Revision ID: 8b4bd637d2c9
Revises: b57f2c8421a7
Create Date: 2026-05-10 00:11:34.197794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.infrastructure.database.models


# revision identifiers, used by Alembic.
revision: str = '8b4bd637d2c9'
down_revision: Union[str, Sequence[str], None] = 'b57f2c8421a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('created_at', src.infrastructure.database.models.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', src.infrastructure.database.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__outbox_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
