"""enhance_models_integrity_and_performance

Revision ID: 6f36769b5729
Revises: 8b4bd637d2c9
Create Date: 2026-05-10 01:59:40.392234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f36769b5729'
down_revision: Union[str, Sequence[str], None] = '8b4bd637d2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__activities__score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix__activities__sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix__activities__timestamp'), ['timestamp'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk__activities__sid__students'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__activities__sid__students'), 'students', ['sid'], ['sid'], ondelete='CASCADE')

    with op.batch_alter_table('advisor_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__advisor_badges__advisor_id'), ['advisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix__advisor_badges__awarded_at'), ['awarded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix__advisor_badges__badge_id'), ['badge_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk__advisor_badges__advisor_id__advisors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__advisor_badges__advisor_id__advisors'), 'advisors', ['advisor_id'], ['advisor_id'], ondelete='CASCADE')

    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__advisors__email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix__advisors__name'), ['name'], unique=False)

    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__background_job_tracker__correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix__background_job_tracker__created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix__background_job_tracker__status'), ['status'], unique=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__cases__assigned_advisor_id'), ['assigned_advisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix__cases__created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix__cases__intervention_status'), ['intervention_status'], unique=False)
        batch_op.create_index(batch_op.f('ix__cases__sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix__cases__updated_at'), ['updated_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk__cases__sid__students'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk__cases__assigned_advisor_id__advisors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__cases__assigned_advisor_id__advisors'), 'advisors', ['assigned_advisor_id'], ['advisor_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk__cases__sid__students'), 'students', ['sid'], ['sid'], ondelete='CASCADE')

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__idempotency_keys__created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.alter_column('case_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.create_index(batch_op.f('ix__intervention_emails__created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix__intervention_emails__status'), ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk__intervention_emails__case_id__cases'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__intervention_emails__case_id__cases'), 'cases', ['case_id'], ['case_id'], ondelete='CASCADE')

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__outbox_events__created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix__outbox_events__processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix__outbox_events__status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix__outbox_events__task_name'), ['task_name'], unique=False)

    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__point_ledger__advisor_id'), ['advisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix__point_ledger__case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix__point_ledger__earned_at'), ['earned_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk__point_ledger__case_id__cases'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk__point_ledger__advisor_id__advisors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__point_ledger__advisor_id__advisors'), 'advisors', ['advisor_id'], ['advisor_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk__point_ledger__case_id__cases'), 'cases', ['case_id'], ['case_id'], ondelete='CASCADE')

    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__student_status_history__anomaly_flag'), ['anomaly_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix__student_status_history__sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix__student_status_history__status_recorded_at'), ['status_recorded_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk__student_status_history__sid__students'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__student_status_history__sid__students'), 'students', ['sid'], ['sid'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__students__current_risk_status'), ['current_risk_status'], unique=False)
        batch_op.create_index(batch_op.f('ix__students__email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix__students__student_name'), ['student_name'], unique=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__user_settings__user_id__user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__user_settings__user_id__user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__user_settings__user_id__user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__user_settings__user_id__user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__students__student_name'))
        batch_op.drop_index(batch_op.f('ix__students__email'))
        batch_op.drop_index(batch_op.f('ix__students__current_risk_status'))

    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__student_status_history__sid__students'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__student_status_history__sid__students'), 'students', ['sid'], ['sid'])
        batch_op.drop_index(batch_op.f('ix__student_status_history__status_recorded_at'))
        batch_op.drop_index(batch_op.f('ix__student_status_history__sid'))
        batch_op.drop_index(batch_op.f('ix__student_status_history__anomaly_flag'))

    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__point_ledger__case_id__cases'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk__point_ledger__advisor_id__advisors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__point_ledger__advisor_id__advisors'), 'advisors', ['advisor_id'], ['advisor_id'])
        batch_op.create_foreign_key(batch_op.f('fk__point_ledger__case_id__cases'), 'cases', ['case_id'], ['case_id'])
        batch_op.drop_index(batch_op.f('ix__point_ledger__earned_at'))
        batch_op.drop_index(batch_op.f('ix__point_ledger__case_id'))
        batch_op.drop_index(batch_op.f('ix__point_ledger__advisor_id'))

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__outbox_events__task_name'))
        batch_op.drop_index(batch_op.f('ix__outbox_events__status'))
        batch_op.drop_index(batch_op.f('ix__outbox_events__processed_at'))
        batch_op.drop_index(batch_op.f('ix__outbox_events__created_at'))

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__intervention_emails__case_id__cases'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__intervention_emails__case_id__cases'), 'cases', ['case_id'], ['case_id'])
        batch_op.drop_index(batch_op.f('ix__intervention_emails__status'))
        batch_op.drop_index(batch_op.f('ix__intervention_emails__created_at'))
        batch_op.alter_column('case_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__idempotency_keys__created_at'))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__cases__sid__students'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk__cases__assigned_advisor_id__advisors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__cases__assigned_advisor_id__advisors'), 'advisors', ['assigned_advisor_id'], ['advisor_id'])
        batch_op.create_foreign_key(batch_op.f('fk__cases__sid__students'), 'students', ['sid'], ['sid'])
        batch_op.drop_index(batch_op.f('ix__cases__updated_at'))
        batch_op.drop_index(batch_op.f('ix__cases__sid'))
        batch_op.drop_index(batch_op.f('ix__cases__intervention_status'))
        batch_op.drop_index(batch_op.f('ix__cases__created_at'))
        batch_op.drop_index(batch_op.f('ix__cases__assigned_advisor_id'))

    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__background_job_tracker__status'))
        batch_op.drop_index(batch_op.f('ix__background_job_tracker__created_at'))
        batch_op.drop_index(batch_op.f('ix__background_job_tracker__correlation_id'))

    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__advisors__name'))
        batch_op.drop_index(batch_op.f('ix__advisors__email'))

    with op.batch_alter_table('advisor_badges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__advisor_badges__advisor_id__advisors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__advisor_badges__advisor_id__advisors'), 'advisors', ['advisor_id'], ['advisor_id'])
        batch_op.drop_index(batch_op.f('ix__advisor_badges__badge_id'))
        batch_op.drop_index(batch_op.f('ix__advisor_badges__awarded_at'))
        batch_op.drop_index(batch_op.f('ix__advisor_badges__advisor_id'))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__activities__sid__students'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk__activities__sid__students'), 'students', ['sid'], ['sid'])
        batch_op.drop_index(batch_op.f('ix__activities__timestamp'))
        batch_op.drop_index(batch_op.f('ix__activities__sid'))
        batch_op.drop_index(batch_op.f('ix__activities__score'))

    # ### end Alembic commands ###
