"""add_adaptive_signals_to_history

Revision ID: 83c089f45bef
Revises: c60b1f6db06e
Create Date: 2026-05-15 14:11:59.547545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c089f45bef'
down_revision: Union[str, Sequence[str], None] = 'c60b1f6db06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_normalized_drift', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('trend_score', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('systemic_breadth', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.drop_column('systemic_breadth')
        batch_op.drop_column('confidence')
        batch_op.drop_column('trend_score')
        batch_op.drop_column('avg_normalized_drift')

    # ### end Alembic commands ###
