"""add_missing_fk_indexes

Revision ID: 1ac7f93369c3
Revises: 481aad74b9f2
Create Date: 2026-05-11 17:01:56.324797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac7f93369c3'
down_revision: Union[str, Sequence[str], None] = '481aad74b9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__appointments__case_id'), ['case_id'], unique=False)

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__intervention_emails__case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__intervention_emails__case_id'))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__appointments__case_id'))

    # ### end Alembic commands ###
