"""add_workinghours_and_dateoff_tables

Revision ID: 481aad74b9f2
Revises: 9a00bccac137
Create Date: 2026-05-10 20:11:50.818726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481aad74b9f2'
down_revision: Union[str, Sequence[str], None] = '9a00bccac137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_days_off',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.advisor_id'], name=op.f('fk__advisor_days_off__advisor_id__advisors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__advisor_days_off'))
    )
    with op.batch_alter_table('advisor_days_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__advisor_days_off__advisor_id'), ['advisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix__advisor_days_off__date'), ['date'], unique=False)

    op.create_table('advisor_working_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.advisor_id'], name=op.f('fk__advisor_working_hours__advisor_id__advisors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__advisor_working_hours'))
    )
    with op.batch_alter_table('advisor_working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__advisor_working_hours__advisor_id'), ['advisor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_working_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__advisor_working_hours__advisor_id'))

    op.drop_table('advisor_working_hours')
    with op.batch_alter_table('advisor_days_off', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__advisor_days_off__date'))
        batch_op.drop_index(batch_op.f('ix__advisor_days_off__advisor_id'))

    op.drop_table('advisor_days_off')
    # ### end Alembic commands ###
