"""add_ai_and_signature_user_settings

Revision ID: 2b8556302991
Revises: 83c089f45bef
Create Date: 2026-05-16 20:20:44.589846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8556302991'
down_revision: Union[str, Sequence[str], None] = '83c089f45bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_tone', sa.String(), nullable=False, server_default='warm'))
        batch_op.add_column(sa.Column('safety_rules', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('safety_rules')
        batch_op.drop_column('ai_tone')
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
