"""add_admin_dashboard_columns

Revision ID: c60b1f6db06e
Revises: 4c4866c96803
Create Date: 2026-05-15 10:28:53.536562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.infrastructure.database.models


# revision identifiers, used by Alembic.
revision: str = 'c60b1f6db06e'
down_revision: Union[str, Sequence[str], None] = '4c4866c96803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('GRADE_DROP', 'LOW_ATTENDANCE', 'MISSING_ASSIGNMENTS', 'LOW_ENGAGEMENT', 'FINANCIAL_STRESS', 'PERSONAL_ISSUES', 'OTHER', 'UNKNOWN', name='riskreason').create(op.get_bind())
    sa.Enum('NORMAL', 'ELEVATED', 'CRITICAL', 'UNKNOWN', name='riskstatus').create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_reason', sa.Enum('GRADE_DROP', 'LOW_ATTENDANCE', 'MISSING_ASSIGNMENTS', 'LOW_ENGAGEMENT', 'FINANCIAL_STRESS', 'PERSONAL_ISSUES', 'OTHER', 'UNKNOWN', name='riskreason'), nullable=False, server_default='UNKNOWN'))
        batch_op.add_column(sa.Column('first_interaction_at', src.infrastructure.database.models.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('initial_gpa', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('final_gpa', sa.Double(), nullable=True))
        batch_op.create_index(batch_op.f('ix__cases__risk_reason'), ['risk_reason'], unique=False)

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_nudge', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('responded_at', src.infrastructure.database.models.UTCDateTime(timezone=True), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_gpa', sa.Double(), nullable=True))
        batch_op.alter_column('current_risk_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NORMAL', 'ELEVATED', 'CRITICAL', 'UNKNOWN', name='riskstatus'),
               existing_nullable=False,
               postgresql_using='current_risk_status::riskstatus')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('current_risk_status',
               existing_type=sa.Enum('NORMAL', 'ELEVATED', 'CRITICAL', 'UNKNOWN', name='riskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('cumulative_gpa')

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.drop_column('responded_at')
        batch_op.drop_column('is_nudge')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__cases__risk_reason'))
        batch_op.drop_column('final_gpa')
        batch_op.drop_column('initial_gpa')
        batch_op.drop_column('first_interaction_at')
        batch_op.drop_column('risk_reason')

    sa.Enum('GRADE_DROP', 'LOW_ATTENDANCE', 'MISSING_ASSIGNMENTS', 'LOW_ENGAGEMENT', 'FINANCIAL_STRESS', 'PERSONAL_ISSUES', 'OTHER', 'UNKNOWN', name='riskreason').drop(op.get_bind())
    # ### end Alembic commands ###
