"""add_version_to_intervention_email

Revision ID: b57f2c8421a7
Revises: f7428a316ae5
Create Date: 2026-05-09 23:09:01.869866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57f2c8421a7'
down_revision: Union[str, Sequence[str], None] = 'f7428a316ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('intervention_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('NEW', 'ACCEPTED', 'SENT', 'BOOKED', 'SUPPORTING', 'PENDING_REVIEW', 'RESOLVED', 'FAILED', 'DISMISSED', 'EXPIRED', name='interventionstatus'),
               existing_nullable=False)

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('intervention_status',
               existing_type=sa.Enum('NEW', 'ACCEPTED', 'SENT', 'BOOKED', 'SUPPORTING', 'PENDING_REVIEW', 'RESOLVED', 'FAILED', 'DISMISSED', 'EXPIRED', name='interventionstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
