"""add_notifications_table

Revision ID: b5bdd11fd299
Revises: 2b8556302991
Create Date: 2026-05-17 10:51:13.031192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.infrastructure.database.models


# revision identifiers, used by Alembic.
revision: str = 'b5bdd11fd299'
down_revision: Union[str, Sequence[str], None] = '2b8556302991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'SUCCESS', 'ERROR', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', src.infrastructure.database.models.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__notifications__user_id__user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__notifications__created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix__notifications__user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__notifications__user_id'))
        batch_op.drop_index(batch_op.f('ix__notifications__created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
