"""add_appointments_table

Revision ID: 9a00bccac137
Revises: 6f36769b5729
Create Date: 2026-05-10 02:33:47.104584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.infrastructure.database.models


# revision identifiers, used by Alembic.
revision: str = '9a00bccac137'
down_revision: Union[str, Sequence[str], None] = '6f36769b5729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_time', src.infrastructure.database.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('meeting_method', sa.Enum('ONLINE', 'IN_PERSON', name='meetingmethod'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', src.infrastructure.database.models.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk__appointments__case_id__cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id', name=op.f('pk__appointments')),
    sa.UniqueConstraint('case_id', name='uq_appointments_case_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__appointments__created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__appointments__created_at'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
