"""Add advisor_badges table

Revision ID: 1a54b5ea1a5b
Revises: f9ff11a14bee
Create Date: 2026-05-03 16:04:43.228149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a54b5ea1a5b'
down_revision: Union[str, Sequence[str], None] = 'f9ff11a14bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_badges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('awarded_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.advisor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisor_id', 'badge_id', name='uq_advisor_badge')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advisor_badges')
    # ### end Alembic commands ###
