"""fix uuid types

Revision ID: 65576d03c79c
Revises: f2da6c2cdc29
Create Date: 2026-05-03 13:35:03.747779

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65576d03c79c'
down_revision: Union[str, Sequence[str], None] = 'f2da6c2cdc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.CHAR(length=32),
               type_=fastapi_users_db_sqlalchemy.generics.GUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=fastapi_users_db_sqlalchemy.generics.GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
