"""add assigned_advisor_id to cases

Revision ID: 94d2bd39c0a6
Revises: 9f1ec9cbec66
Create Date: 2026-05-02 23:12:16.307836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d2bd39c0a6'
down_revision: Union[str, Sequence[str], None] = '9f1ec9cbec66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_advisor_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_cases_assigned_advisor_id', 'advisors', ['assigned_advisor_id'], ['advisor_id'])

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_intervention_emails_case_id', ['case_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.drop_constraint('uq_intervention_emails_case_id', type_='unique')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cases_assigned_advisor_id', type_='foreignkey')
        batch_op.drop_column('assigned_advisor_id')

    # ### end Alembic commands ###
