"""add_cases_and_enhance_job_tracker

Revision ID: b1c75aa208ce
Revises: cadbc9ef2310
Create Date: 2026-05-02 18:30:21.964471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c75aa208ce'
down_revision: Union[str, Sequence[str], None] = 'cadbc9ef2310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('correlation_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('correlation_type', sa.String(), nullable=True))
        batch_op.drop_column('sid')

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_intervention_emails_case_id', 'cases', ['case_id'], ['case_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.drop_constraint('fk_intervention_emails_case_id', type_='foreignkey')
        batch_op.drop_column('case_id')

    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key('fk_background_job_tracker_sid', 'students', ['sid'], ['sid'])
        batch_op.drop_column('correlation_type')
        batch_op.drop_column('correlation_id')
        batch_op.drop_column('progress')
        batch_op.drop_column('error_message')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('created_at')

    op.drop_table('cases')
    # ### end Alembic commands ###
