"""add composite index on advisor_points_ledger

Revision ID: bd0aa53c2057
Revises: cadbc9ef2310
Create Date: 2026-05-02 18:10:19.420326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0aa53c2057'
down_revision: Union[str, Sequence[str], None] = 'cadbc9ef2310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_points_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_advisor_sid_action', ['advisor_id', 'sid', 'action_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_points_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_advisor_sid_action')

    # ### end Alembic commands ###
