"""extract_user_settings_and_job_tracker

Revision ID: cadbc9ef2310
Revises: b6646f998258
Create Date: 2026-05-02 16:37:18.692767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cadbc9ef2310'
down_revision: Union[str, Sequence[str], None] = 'b6646f998258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_job_tracker',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('auto_draft_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('draft_job_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_draft_enabled')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_draft_enabled', sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_job_id', sa.CHAR(length=32), nullable=True))

    op.drop_table('user_settings')
    op.drop_table('background_job_tracker')
    # ### end Alembic commands ###
