"""add_unique_constraint_on_case_email

Revision ID: f2da6c2cdc29
Revises: a73dbcc304e6
Create Date: 2026-05-02 21:21:24.970996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2da6c2cdc29'
down_revision: Union[str, Sequence[str], None] = 'a73dbcc304e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_intervention_emails_case_id', ['case_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.drop_constraint('uq_intervention_emails_case_id', type_='unique')

    # ### end Alembic commands ###
