"""add_risk_status_field

Revision ID: 426b8aba808a
Revises: ef96aa80c6b7
Create Date: 2026-05-05 12:44:20.676860

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '426b8aba808a'
down_revision: str | Sequence[str] | None = 'ef96aa80c6b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True))
        batch_op.drop_column('version')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###
