"""update_config

Revision ID: ef96aa80c6b7
Revises:
Create Date: 2026-05-04 22:42:36.155857

"""

from collections.abc import Sequence
from typing import Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef96aa80c6b7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'background_job_tracker',
        sa.Column('job_id', sa.Uuid(), nullable=False),
        sa.Column('job_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=False),
        sa.Column('correlation_id', sa.Uuid(), nullable=True),
        sa.Column('correlation_type', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('job_id', name=op.f('pk__background_job_tracker')),
    )
    op.create_table(
        'idempotency_keys',
        sa.Column('key', sa.Uuid(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('key', name=op.f('pk__idempotency_keys')),
    )
    op.create_table(
        'students',
        sa.Column('sid', sa.Uuid(), nullable=False),
        sa.Column('student_name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('major', sa.String(), nullable=False),
        sa.Column('current_risk_status', sa.String(), nullable=False),
        sa.Column('intervention_status', sa.String(), nullable=False),
        sa.Column('last_notified_timestamp', sa.Double(), nullable=False),
        sa.Column('last_notified_satisfaction', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('sid', name=op.f('pk__students')),
    )
    op.create_table(
        'user',
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('hashed_password', sa.String(length=1024), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__user')),
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__user__email'), ['email'], unique=True)

    op.create_table(
        'activities',
        sa.Column('activity_id', sa.Uuid(), nullable=False),
        sa.Column('sid', sa.Uuid(), nullable=False),
        sa.Column('course_id', sa.String(), nullable=True),
        sa.Column('course_name', sa.String(), nullable=True),
        sa.Column('test_type', sa.String(), nullable=True),
        sa.Column('score', sa.Double(), nullable=True),
        sa.Column('timestamp', sa.Double(), nullable=True),
        sa.Column('academic_year', sa.Integer(), nullable=True),
        sa.Column('semester', sa.Integer(), nullable=True),
        sa.Column('week', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['sid'], ['students.sid'], name=op.f('fk__activities__sid__students')
        ),
        sa.PrimaryKeyConstraint('activity_id', name=op.f('pk__activities')),
    )
    op.create_table(
        'advisors',
        sa.Column('advisor_id', sa.Uuid(), nullable=False),
        sa.Column(
            'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True
        ),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('fk__advisors__user_id__user')
        ),
        sa.PrimaryKeyConstraint('advisor_id', name=op.f('pk__advisors')),
        sa.UniqueConstraint('user_id', name=op.f('uq__advisors__user_id')),
    )
    op.create_table(
        'student_status_history',
        sa.Column('history_id', sa.Uuid(), nullable=False),
        sa.Column('sid', sa.Uuid(), nullable=False),
        sa.Column('academic_year', sa.Integer(), nullable=True),
        sa.Column('semester', sa.Integer(), nullable=True),
        sa.Column('week', sa.Integer(), nullable=True),
        sa.Column('baseline_avg', sa.Double(), nullable=True),
        sa.Column('baseline_std', sa.Double(), nullable=True),
        sa.Column('current_score_avg', sa.Double(), nullable=True),
        sa.Column('z_score', sa.Double(), nullable=True),
        sa.Column('anomaly_flag', sa.String(), nullable=True),
        sa.Column(
            'status_recorded_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['sid'],
            ['students.sid'],
            name=op.f('fk__student_status_history__sid__students'),
        ),
        sa.PrimaryKeyConstraint('history_id', name=op.f('pk__student_status_history')),
    )
    op.create_table(
        'user_settings',
        sa.Column(
            'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column('auto_draft_enabled', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('fk__user_settings__user_id__user')
        ),
        sa.PrimaryKeyConstraint('user_id', name=op.f('pk__user_settings')),
    )
    op.create_table(
        'advisor_badges',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('advisor_id', sa.Uuid(), nullable=False),
        sa.Column('badge_id', sa.String(), nullable=False),
        sa.Column(
            'awarded_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['advisor_id'],
            ['advisors.advisor_id'],
            name=op.f('fk__advisor_badges__advisor_id__advisors'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__advisor_badges')),
        sa.UniqueConstraint('advisor_id', 'badge_id', name='uq_advisor_badge'),
    )
    op.create_table(
        'cases',
        sa.Column('case_id', sa.Uuid(), nullable=False),
        sa.Column('sid', sa.Uuid(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('assigned_advisor_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['assigned_advisor_id'],
            ['advisors.advisor_id'],
            name=op.f('fk__cases__assigned_advisor_id__advisors'),
        ),
        sa.ForeignKeyConstraint(
            ['sid'], ['students.sid'], name=op.f('fk__cases__sid__students')
        ),
        sa.PrimaryKeyConstraint('case_id', name=op.f('pk__cases')),
    )
    op.create_table(
        'intervention_emails',
        sa.Column('email_id', sa.Uuid(), nullable=False),
        sa.Column('sid', sa.Uuid(), nullable=False),
        sa.Column('case_id', sa.Uuid(), nullable=True),
        sa.Column('advisor_id', sa.Uuid(), nullable=True),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ['advisor_id'],
            ['advisors.advisor_id'],
            name=op.f('fk__intervention_emails__advisor_id__advisors'),
        ),
        sa.ForeignKeyConstraint(
            ['case_id'],
            ['cases.case_id'],
            name=op.f('fk__intervention_emails__case_id__cases'),
        ),
        sa.ForeignKeyConstraint(
            ['sid'],
            ['students.sid'],
            name=op.f('fk__intervention_emails__sid__students'),
        ),
        sa.PrimaryKeyConstraint('email_id', name=op.f('pk__intervention_emails')),
        sa.UniqueConstraint('case_id', name='uq_intervention_emails_case_id'),
    )
    op.create_table(
        'tasks',
        sa.Column('task_id', sa.Uuid(), nullable=False),
        sa.Column('case_id', sa.Uuid(), nullable=False),
        sa.Column('action_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('points_reward', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('completed_by_advisor_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['case_id'], ['cases.case_id'], name=op.f('fk__tasks__case_id__cases')
        ),
        sa.ForeignKeyConstraint(
            ['completed_by_advisor_id'],
            ['advisors.advisor_id'],
            name=op.f('fk__tasks__completed_by_advisor_id__advisors'),
        ),
        sa.PrimaryKeyConstraint('task_id', name=op.f('pk__tasks')),
    )
    op.create_table(
        'point_ledger',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('advisor_id', sa.Uuid(), nullable=True),
        sa.Column('task_id', sa.Uuid(), nullable=True),
        sa.Column('points', sa.Integer(), nullable=True),
        sa.Column(
            'timestamp',
            sa.TIMESTAMP(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['advisor_id'],
            ['advisors.advisor_id'],
            name=op.f('fk__point_ledger__advisor_id__advisors'),
        ),
        sa.ForeignKeyConstraint(
            ['task_id'],
            ['tasks.task_id'],
            name=op.f('fk__point_ledger__task_id__tasks'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__point_ledger')),
    )
    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.create_index(
            'ix_ledger_advisor_task', ['advisor_id', 'task_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_advisor_task')

    op.drop_table('point_ledger')
    op.drop_table('tasks')
    op.drop_table('intervention_emails')
    op.drop_table('cases')
    op.drop_table('advisor_badges')
    op.drop_table('user_settings')
    op.drop_table('student_status_history')
    op.drop_table('advisors')
    op.drop_table('activities')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__user__email'))

    op.drop_table('user')
    op.drop_table('students')
    op.drop_table('idempotency_keys')
    op.drop_table('background_job_tracker')
    # ### end Alembic commands ###
