"""enforce_timezone_aware_datetime

Revision ID: a3e26ba4a778
Revises: e5312800103a
Create Date: 2026-05-05 17:34:29.831409

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a3e26ba4a778'
down_revision: str | Sequence[str] | None = 'e5312800103a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column(
            'timestamp',
            existing_type=sa.DOUBLE(),
            type_=src.infrastructure.database.models.UTCDateTime(),
            existing_nullable=True,
        )

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'last_notified_timestamp',
            existing_type=sa.DOUBLE(),
            type_=src.infrastructure.database.models.UTCDateTime(),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'last_notified_timestamp',
            existing_type=src.infrastructure.database.models.UTCDateTime(),
            type_=sa.DOUBLE(),
            nullable=False,
        )

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column(
            'timestamp',
            existing_type=src.infrastructure.database.models.UTCDateTime(),
            type_=sa.DOUBLE(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
