"""enforce_timezone_aware_datetime

Revision ID: e5312800103a
Revises: 426b8aba808a
Create Date: 2026-05-05 17:03:36.679425

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e5312800103a'
down_revision: str | Sequence[str] | None = '426b8aba808a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisor_badges', schema=None) as batch_op:
        batch_op.alter_column(
            'awarded_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )
        batch_op.alter_column(
            'started_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'completed_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )
        batch_op.alter_column(
            'assigned_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'closed_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )
        batch_op.alter_column(
            'sent_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'earned_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.alter_column(
            'status_recorded_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )
        batch_op.alter_column(
            'completed_at',
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column(
            'completed_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.alter_column(
            'status_recorded_at',
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'timestamp',
                sa.TIMESTAMP(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.drop_column('earned_at')

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.alter_column(
            'sent_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column(
            'closed_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'assigned_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.alter_column(
            'completed_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'started_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    with op.batch_alter_table('advisor_badges', schema=None) as batch_op:
        batch_op.alter_column(
            'awarded_at',
            existing_type=sa.DateTime(timezone=True),
            type_=sa.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'),
        )

    # ### end Alembic commands ###
