"""update_unique_constraints

Revision ID: 80f09dd4f98e
Revises: a3e26ba4a778
Create Date: 2026-05-06 15:59:48.496448

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80f09dd4f98e'
down_revision: str | Sequence[str] | None = 'a3e26ba4a778'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('office', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'updated_at',
                src.infrastructure.database.models.UTCDateTime(),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('office')
        batch_op.drop_column('faculty')
        batch_op.drop_column('phone')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
