"""remove_task_model

Revision ID: ec1beba8c7e7
Revises: 80f09dd4f98e
Create Date: 2026-05-08 09:58:04.054835

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec1beba8c7e7'
down_revision: str | Sequence[str] | None = '80f09dd4f98e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.alter_column('name', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('email', existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.alter_column(
            'correlation_id', existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            'correlation_type', existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column('job_type')
        batch_op.drop_column('progress')
        batch_op.drop_column('error_message')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'intervention_status',
                sa.Enum(
                    'NEW',
                    'ACCEPTED',
                    'SENT',
                    'BOOKED',
                    'SUPPORTING',
                    'RESOLVED',
                    'DISMISSED',
                    'EXPIRED',
                    name='interventionstatus',
                ),
                nullable=False,
            )
        )
        batch_op.drop_column('status')

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_constraint(
            batch_op.f('fk__intervention_emails__sid__students'), type_='foreignkey'
        )
        batch_op.drop_constraint(
            batch_op.f('fk__intervention_emails__advisor_id__advisors'),
            type_='foreignkey',
        )
        batch_op.drop_column('advisor_id')
        batch_op.drop_column('sid')

    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('action', sa.String(), nullable=False))
        batch_op.alter_column(
            'advisor_id', existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.alter_column('points', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_index(batch_op.f('ix_ledger_advisor_task'))
        batch_op.create_index(
            'ix_ledger_advisor_case', ['advisor_id', 'case_id'], unique=False
        )
        batch_op.drop_constraint(
            batch_op.f('fk__point_ledger__task_id__tasks'), type_='foreignkey'
        )
        batch_op.create_foreign_key(
            batch_op.f('fk__point_ledger__case_id__cases'),
            'cases',
            ['case_id'],
            ['case_id'],
        )
        batch_op.drop_column('task_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column(
            'student_name', existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column('intervention_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('intervention_status', sa.VARCHAR(), nullable=False)
        )
        batch_op.alter_column('student_name', existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table('point_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.CHAR(length=32), nullable=True))
        batch_op.drop_constraint(
            batch_op.f('fk__point_ledger__case_id__cases'), type_='foreignkey'
        )
        batch_op.create_foreign_key(
            batch_op.f('fk__point_ledger__task_id__tasks'),
            'tasks',
            ['task_id'],
            ['task_id'],
        )
        batch_op.drop_index('ix_ledger_advisor_task')
        batch_op.create_index(
            batch_op.f('ix_ledger_advisor_task'),
            ['advisor_id', 'task_id'],
            unique=False,
        )
        batch_op.alter_column('points', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            'advisor_id', existing_type=sa.CHAR(length=32), nullable=True
        )
        batch_op.drop_column('action')
        batch_op.drop_column('case_id')

    with op.batch_alter_table('intervention_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.CHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('advisor_id', sa.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f('fk__intervention_emails__advisor_id__advisors'),
            'advisors',
            ['advisor_id'],
            ['advisor_id'],
        )
        batch_op.create_foreign_key(
            batch_op.f('fk__intervention_emails__sid__students'),
            'students',
            ['sid'],
            ['sid'],
        )
        batch_op.alter_column('status', existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('intervention_status')

    with op.batch_alter_table('background_job_tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('job_type', sa.VARCHAR(), nullable=False))
        batch_op.alter_column(
            'correlation_type', existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            'correlation_id', existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table('advisors', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column('name', existing_type=sa.VARCHAR(), nullable=True)

    op.create_table(
        'tasks',
        sa.Column('task_id', sa.CHAR(length=32), nullable=False),
        sa.Column('case_id', sa.CHAR(length=32), nullable=False),
        sa.Column('action_type', sa.VARCHAR(), nullable=False),
        sa.Column('status', sa.VARCHAR(), nullable=False),
        sa.Column('points_reward', sa.INTEGER(), nullable=False),
        sa.Column(
            'created_at',
            sa.DATETIME(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('completed_at', sa.DATETIME(), nullable=True),
        sa.Column('completed_by_advisor_id', sa.CHAR(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ['case_id'], ['cases.case_id'], name=op.f('fk__tasks__case_id__cases')
        ),
        sa.ForeignKeyConstraint(
            ['completed_by_advisor_id'],
            ['advisors.advisor_id'],
            name=op.f('fk__tasks__completed_by_advisor_id__advisors'),
        ),
        sa.PrimaryKeyConstraint('task_id', name=op.f('pk__tasks')),
    )
    # ### end Alembic commands ###
