"""Main entry point for the Agent Assistant API.

This module initializes the FastAPI application, configures middleware,
and includes the API routers for the agent's functionality.
"""

from dotenv import load_dotenv

load_dotenv()

import time
from typing import Any

from fastapi import APIRouter, FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware

from src.api.routes import alerts, data, health, query
from src.telemetry.logger import logger

app = FastAPI(
    title="Agent Assistant API",
    description="API to interact with the LangGraph Agent for data analysis and visualization.",
    version="1.0.0",
)

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust this for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Logging Middleware
@app.middleware("http")
async def log_requests(request: Request, call_next: Any) -> Response:
    """Logs the details of incoming HTTP requests and their processing time.

    Args:
        request: The incoming FastAPI request object.
        call_next: The next middleware or endpoint handler in the pipeline.

    Returns:
        The HTTP response generated by the application.
    """
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    logger.info(
        f"HTTP: {request.method} {request.url.path} - Status: {response.status_code} - Duration: {process_time:.2f}s",
    )
    return response

# API v1 Router
api_v1_router = APIRouter(prefix="/api/v1")

@api_v1_router.get("/")
async def root() -> dict[str, str]:
    """Provides a welcome message and documentation link for the API root.

    Returns:
        A dictionary containing a welcome message and the API documentation path.
    """
    return {
        "message": "Welcome to the Agent Assistant API v1. Access /docs for Swagger documentation.",
        "docs": "/docs",
    }

# Include routers into the versioned API router
api_v1_router.include_router(health.router)
api_v1_router.include_router(query.router)
api_v1_router.include_router(data.router)
api_v1_router.include_router(alerts.router)

# Include the versioned API router into the app
app.include_router(api_v1_router)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
