"""Main entry point for the Agent Assistant API.

This module initializes the FastAPI application, configures middleware,
and includes the API routers for the agent's functionality.
"""

import time
from collections.abc import Awaitable, Callable

from fastapi import APIRouter, Depends, FastAPI, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from src.api.auth import UserRole, auth_backend, check_role, fastapi_users
from src.api.lifecycle import lifespan
from src.api.models.auth import UserCreate, UserRead, UserUpdate
from src.api.routes import advisors, alerts, data, health, jobs, query, users
from src.telemetry.logger import logger
from src.utils.env import getenv

app = FastAPI(
    title='Agent Assistant API',
    description='API to interact with the LangGraph Agent for data analysis and visualization.',
    version='1.0.0',
    lifespan=lifespan,
)

# CORS Configuration
# Read allowed origins from environment variable, default to localhost:3000
allowed_origins_str = getenv("ALLOWED_ORIGINS", "http://localhost:3000")
allowed_origins = [origin.strip() for origin in allowed_origins_str.split(",") if origin.strip()]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Simple In-Memory Rate Limiting
# In production, use Redis or a dedicated library like slowapi
rate_limit_store: dict[str, list[float]] = {}
RATE_LIMIT_CALLS = 100
RATE_LIMIT_WINDOW = 60  # seconds


@app.middleware('http')
async def rate_limit_middleware(
    request: Request,
    call_next: Callable[[Request], Awaitable[Response]],
) -> Response:
    """Simple rate limiting middleware based on client host."""
    client_ip = request.client.host if request.client else "unknown"
    now = time.time()

    # Clean up old timestamps
    if client_ip in rate_limit_store:
        rate_limit_store[client_ip] = [
            ts for ts in rate_limit_store[client_ip] if now - ts < RATE_LIMIT_WINDOW
        ]
    else:
        rate_limit_store[client_ip] = []

    if len(rate_limit_store[client_ip]) >= RATE_LIMIT_CALLS:
        logger.warning(f"Rate Limit Exceeded for {client_ip}")
        return JSONResponse(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            content={"detail": "Too many requests. Please try again later."},
        )

    rate_limit_store[client_ip].append(now)
    return await call_next(request)


# Logging Middleware
@app.middleware('http')
async def log_requests(
    request: Request,
    call_next: Callable[[Request], Awaitable[Response]],
) -> Response:
    """Logs the details of incoming HTTP requests and their processing time.

    Args:
        request: The incoming FastAPI request object.
        call_next: The next middleware or endpoint handler in the pipeline.

    Returns:
        The HTTP response generated by the application.
    """
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    logger.info(
        f"HTTP: {request.method} {request.url.path} - Status: {response.status_code} - Duration: {process_time:.2f}s",
    )
    return response


@app.exception_handler(Exception)
async def global_exception_handler(_request: Request, exc: Exception) -> JSONResponse:
    """Catches all unhandled exceptions and returns a sanitized JSON response."""
    logger.error(f'Unhandled Exception: {exc}', exc_info=True)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            'detail': 'An unexpected internal error occurred.',
            'type': type(exc).__name__,
        },
    )


@app.exception_handler(ValueError)
async def value_error_handler(_request: Request, exc: ValueError) -> JSONResponse:
    """Handles validation errors specifically."""
    logger.warning(f'Validation Error: {exc}')
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content={
            'detail': str(exc),
            'type': 'ValidationError',
        },
    )


try:
    from sqlglot import ParseError as SQLParseError
except ImportError:
    SQLParseError = Exception


@app.exception_handler(SQLParseError)
async def sql_parse_error_handler(_request: Request, exc: Exception) -> JSONResponse:
    """Handles SQL parsing errors specifically."""
    logger.warning(f'SQL Parse Error: {exc}')
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content={
            'detail': 'The generated or provided SQL query is invalid.',
            'type': 'SQLParseError',
        },
    )


# API v1 Router
api_v1_router = APIRouter(prefix="/api/v1")

# Include Auth routes
api_v1_router.include_router(
    fastapi_users.get_auth_router(auth_backend),
    prefix="/auth/jwt",
    tags=["auth"],
)
api_v1_router.include_router(
    fastapi_users.get_register_router(UserRead, UserCreate),
    prefix="/auth",
    tags=["auth"],
)

# User Management
api_v1_router.include_router(users.router)

@api_v1_router.get("/")
async def root() -> dict[str, str]:
    """Provides a welcome message and documentation link for the API root.

    Returns:
        A dictionary containing a welcome message and the API documentation path.
    """
    return {
        "message": "Welcome to the Agent Assistant API v1. Access /docs for Swagger documentation.",
        "docs": "/docs",
    }

# Include routers into the versioned API router
api_v1_router.include_router(health.router)
api_v1_router.include_router(jobs.router)
api_v1_router.include_router(query.router)
api_v1_router.include_router(data.router)
api_v1_router.include_router(alerts.router)
api_v1_router.include_router(advisors.router)

# Include the versioned API router into the app
app.include_router(api_v1_router)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
