# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DiscoveryRequest": types.DiscoveryRequest,
    "stream_types.DiscoveryRequest": stream_types.DiscoveryRequest,

    "types.GeneratedSQL": types.GeneratedSQL,
    "stream_types.GeneratedSQL": stream_types.GeneratedSQL,

    "types.PlannerTask": types.PlannerTask,
    "stream_types.PlannerTask": stream_types.PlannerTask,

    "types.RequestDBSchema": types.RequestDBSchema,
    "stream_types.RequestDBSchema": stream_types.RequestDBSchema,

    "types.RouterPlan": types.RouterPlan,
    "stream_types.RouterPlan": stream_types.RouterPlan,


}